import { IdentityType } from "../Identity/type";
import { Card } from "./Card";
import { ChengQing } from "./CardClass/ChengQing";
import { DiaoBao } from "./CardClass/DiaoBao";
import { FengYunBianHuan } from "./CardClass/FengYunBianHuan";
import { JieHuo } from "./CardClass/JieHuo";
import { LiYou } from "./CardClass/LiYou";
import { MiLing } from "./CardClass/MiLing";
import { PingHeng } from "./CardClass/PingHeng";
import { PoYi } from "./CardClass/PoYi";
import { ShiTan } from "./CardClass/ShiTan";
import { UnknownCard } from "./CardClass/UnknownCard";
import { WeiBi } from "./CardClass/WeiBi";
import { WuDao } from "./CardClass/WuDao";
import { CardColor, CardDirection } from "./type";

export const deck: { [index: number]: Card } = {
  0: new UnknownCard(),
  1: new ShiTan({
    id: 1,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.GREEN],
  }),
  2: new ShiTan({
    id: 2,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE],
  }),
  3: new ShiTan({
    id: 3,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.GREEN],
  }),
  4: new ShiTan({
    id: 4,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.BLUE],
  }),
  5: new ShiTan({
    id: 5,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE, IdentityType.GREEN],
  }),
  6: new ShiTan({
    id: 6,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED],
  }),
  7: new ShiTan({
    id: 7,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.GREEN],
  }),
  8: new ShiTan({
    id: 8,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE],
  }),
  9: new ShiTan({
    id: 9,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.GREEN],
  }),
  10: new ShiTan({
    id: 10,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.BLUE],
  }),
  11: new ShiTan({
    id: 11,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE, IdentityType.GREEN],
  }),
  12: new ShiTan({
    id: 12,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED],
  }),
  13: new ShiTan({
    id: 13,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.GREEN],
  }),
  14: new ShiTan({
    id: 14,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE],
  }),
  15: new ShiTan({
    id: 15,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.GREEN],
  }),
  16: new ShiTan({
    id: 16,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED, IdentityType.BLUE],
  }),
  17: new ShiTan({
    id: 17,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.BLUE, IdentityType.GREEN],
  }),
  18: new ShiTan({
    id: 18,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
    drawCardColor: [IdentityType.RED],
  }),
  19: new PingHeng({
    id: 19,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  20: new PingHeng({
    id: 20,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  21: new PingHeng({
    id: 21,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  22: new PingHeng({
    id: 22,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  23: new PingHeng({
    id: 23,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  24: new PingHeng({
    id: 24,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  25: new PingHeng({
    id: 25,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  26: new PingHeng({
    id: 26,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  27: new WeiBi({
    id: 27,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  28: new WeiBi({
    id: 28,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  29: new WeiBi({
    id: 29,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  30: new WeiBi({
    id: 30,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  31: new WeiBi({
    id: 31,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  32: new WeiBi({
    id: 32,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  33: new WeiBi({
    id: 33,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  34: new WeiBi({
    id: 34,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  35: new WeiBi({
    id: 35,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  36: new WeiBi({
    id: 36,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  37: new WeiBi({
    id: 37,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  38: new WeiBi({
    id: 38,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  39: new WeiBi({
    id: 39,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  40: new WeiBi({
    id: 40,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  41: new LiYou({
    id: 41,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  42: new LiYou({
    id: 42,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  43: new LiYou({
    id: 43,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  44: new LiYou({
    id: 44,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  45: new LiYou({
    id: 45,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  46: new LiYou({
    id: 46,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  47: new LiYou({
    id: 47,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  48: new LiYou({
    id: 48,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  49: new ChengQing({
    id: 49,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: true,
  }),
  50: new ChengQing({
    id: 50,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: true,
  }),
  51: new ChengQing({
    id: 51,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  52: new ChengQing({
    id: 52,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  53: new ChengQing({
    id: 53,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: true,
  }),
  54: new ChengQing({
    id: 54,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: true,
  }),
  55: new ChengQing({
    id: 55,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  56: new ChengQing({
    id: 56,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  57: new PoYi({
    id: 57,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  58: new PoYi({
    id: 58,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  59: new PoYi({
    id: 59,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  60: new PoYi({
    id: 60,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  61: new PoYi({
    id: 61,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: true,
  }),
  62: new PoYi({
    id: 62,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  63: new PoYi({
    id: 63,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  64: new PoYi({
    id: 64,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  65: new PoYi({
    id: 65,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  66: new PoYi({
    id: 66,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: true,
  }),
  67: new DiaoBao({
    id: 67,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: false,
  }),
  68: new DiaoBao({
    id: 68,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  69: new DiaoBao({
    id: 69,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  70: new DiaoBao({
    id: 70,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: false,
  }),
  71: new DiaoBao({
    id: 71,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  72: new DiaoBao({
    id: 72,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  73: new DiaoBao({
    id: 73,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  74: new DiaoBao({
    id: 74,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  75: new DiaoBao({
    id: 75,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  76: new DiaoBao({
    id: 76,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  77: new DiaoBao({
    id: 77,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  78: new DiaoBao({
    id: 78,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  79: new JieHuo({
    id: 79,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: false,
  }),
  80: new JieHuo({
    id: 80,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: false,
  }),
  81: new JieHuo({
    id: 81,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: true,
  }),
  82: new JieHuo({
    id: 82,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: false,
  }),
  83: new JieHuo({
    id: 83,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: false,
  }),
  84: new JieHuo({
    id: 84,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: true,
  }),
  85: new JieHuo({
    id: 85,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  86: new JieHuo({
    id: 86,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  87: new JieHuo({
    id: 87,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  88: new JieHuo({
    id: 88,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  89: new JieHuo({
    id: 89,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  90: new JieHuo({
    id: 90,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: false,
  }),
  91: new WuDao({
    id: 91,
    color: [CardColor.RED],
    direction: CardDirection.UP,
    lockable: false,
  }),
  92: new WuDao({
    id: 92,
    color: [CardColor.RED],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  93: new WuDao({
    id: 93,
    color: [CardColor.RED],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  94: new WuDao({
    id: 94,
    color: [CardColor.BLUE],
    direction: CardDirection.UP,
    lockable: false,
  }),
  95: new WuDao({
    id: 95,
    color: [CardColor.BLUE],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  96: new WuDao({
    id: 96,
    color: [CardColor.BLUE],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  97: new WuDao({
    id: 97,
    color: [CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  98: new WuDao({
    id: 98,
    color: [CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  99: new WuDao({
    id: 99,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.LEFT,
    lockable: false,
  }),
  100: new WuDao({
    id: 100,
    color: [CardColor.RED, CardColor.BLACK],
    direction: CardDirection.RIGHT,
    lockable: false,
  }),
  101: new FengYunBianHuan({
    id: 101,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  102: new FengYunBianHuan({
    id: 102,
    color: [CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
  }),
  103: new MiLing({
    id: 103,
    color: [CardColor.BLUE, CardColor.BLACK],
    direction: CardDirection.UP,
    lockable: true,
    secretColor: [CardColor.BLUE, CardColor.BLACK, CardColor.RED],
  }),
};
