//网络事件，ws收发数据使用
export enum NetworkEvent {
  //toc协议
  ERROR_CODE_TOC = "error_code_toc",
  PAUSE_RECORD_TOC = "pause_record_toc",
  GET_RECORD_LIST_TOC = "get_record_list_toc",
  ADD_ORDER_TOC = "add_order_toc",
  GET_ORDERS_TOC = "get_orders_toc",
  HEART_TOC = "heart_toc",
  ADD_ONE_POSITION_TOC = "add_one_position_toc",
  REMOVE_ONE_POSITION_TOC = "remove_one_position_toc",
  DISPLAY_RECORD_END_TOC = "display_record_end_toc",
  SAVE_RECORD_SUCCESS_TOC = "save_record_success_toc",
  GET_ROOM_INFO_TOC = "get_room_info_toc",
  JOIN_ROOM_TOC = "join_room_toc",
  LEAVE_ROOM_TOC = "leave_room_toc",
  WAIT_FOR_SELECT_ROLE_TOC = "wait_for_select_role_toc",
  AUTO_PLAY_TOC = "auto_play_toc",
  SELECT_ROLE_TOC = "select_role_toc",
  INIT_TOC = "init_toc",
  NOTIFY_ROLE_UPDATE_TOC = "notify_role_update_toc",
  ADD_CARD_TOC = "add_card_toc",
  USE_SHI_TAN_TOC = "use_shi_tan_toc",
  SHOW_SHI_TAN_TOC = "show_shi_tan_toc",
  EXECUTE_SHI_TAN_TOC = "execute_shi_tan_toc",
  SYNC_DECK_NUM_TOC = "sync_deck_num_toc",
  DISCARD_CARD_TOC = "discard_card_toc",
  NOTIFY_PHASE_TOC = "notify_phase_toc",
  USE_LI_YOU_TOC = "use_li_you_toc",
  USE_PING_HENG_TOC = "use_ping_heng_toc",
  WEI_BI_WAIT_FOR_GIVE_CARD_TOC = "wei_bi_wait_for_give_card_toc",
  WEI_BI_GIVE_CARD_TOC = "wei_bi_give_card_toc",
  WEI_BI_SHOW_HAND_CARD_TOC = "wei_bi_show_hand_card_toc",
  USE_CHENG_QING_TOC = "use_cheng_qing_toc",
  SEND_MESSAGE_CARD_TOC = "send_message_card_toc",
  CHOOSE_RECEIVE_TOC = "choose_receive_toc",
  NOTIFY_DYING_TOC = "notify_dying_toc",
  NOTIFY_DIE_TOC = "notify_die_toc",
  NOTIFY_WINNER_TOC = "notify_winner_toc",
  WAIT_FOR_CHENG_QING_TOC = "wait_for_cheng_qing_toc",
  WAIT_FOR_DIE_GIVE_CARD_TOC = "wait_for_die_give_card_toc",
  NOTIFY_DIE_GIVE_CARD_TOC = "notify_die_give_card_toc",
  USE_PO_YI_TOC = "use_po_yi_toc",
  PO_YI_SHOW_TOC = "po_yi_show_toc",
  USE_JIE_HUO_TOC = "use_jie_huo_toc",
  USE_DIAO_BAO_TOC = "use_diao_bao_toc",
  USE_WU_DAO_TOC = "use_wu_dao_toc",
  USE_FENG_YUN_BIAN_HUAN_TOC = "use_feng_yun_bian_huan_toc",
  WAIT_FOR_FENG_YUN_BIAN_HUAN_CHOOSE_CARD_TOC = "wait_for_feng_yun_bian_huan_choose_card_toc",
  FENG_YUN_BIAN_HUAN_CHOOSE_CARD_TOC = "feng_yun_bian_huan_choose_card_toc",
  SKILL_QI_HUO_KE_JU_TOC = "skill_qi_huo_ke_ju_toc",
  SKILL_GUI_ZHA_TOC = "skill_gui_zha_toc",
  SKILL_YI_YA_HUAN_YA_TOC = "skill_yi_ya_huan_ya_toc",
  SKILL_YI_HUA_JIE_MU_TOC = "skill_yi_hua_jie_mu_toc",
  SKILL_TOU_TIAN_TOC = "skill_tou_tian_toc",
  SKILL_HUAN_RI_TOC = "skill_huan_ri_toc",
  SKILL_JI_SONG_TOC = "skill_ji_song_toc",
  SKILL_MIAN_LI_CANG_ZHEN_TOC = "skill_mian_li_cang_zhen_toc",
  SKILL_JIN_SHEN_TOC = "skill_jin_shen_toc",
  SKILL_LIAN_MIN_TOC = "skill_lian_min_toc",
  SKILL_FU_HEI_TOC = "skill_fu_hei_toc",
  SKILL_XIN_SI_CHAO_TOC = "skill_xin_si_chao_toc",
  SKILL_SHI_SI_TOC = "skill_shi_si_toc",
  SKILL_WAIT_FOR_RU_GUI_TOC = "skill_wait_for_ru_gui_toc",
  SKILL_RU_GUI_TOC = "skill_ru_gui_toc",
  SKILL_WAIT_FOR_ZHUAN_JIAO_TOC = "skill_wait_for_zhuan_jiao_toc",
  SKILL_ZHUAN_JIAO_TOC = "skill_zhuan_jiao_toc",
  SKILL_MING_ER_TOC = "skill_ming_er_toc",
  SKILL_JI_ZHI_TOC = "skill_ji_zhi_toc",
  SKILL_WAIT_FOR_CHENG_ZHI_TOC = "skill_wait_for_cheng_zhi_toc",
  SKILL_CHENG_ZHI_TOC = "skill_cheng_zhi_toc",
  SKILL_JIU_JI_A_TOC = "skill_jiu_ji_a_toc",
  SKILL_JIU_JI_B_TOC = "skill_jiu_ji_b_toc",
  SKILL_CHENG_FU_TOC = "skill_cheng_fu_toc",
  SKILL_WAIT_FOR_YI_XIN_TOC = "skill_wait_for_yi_xin_toc",
  SKILL_YI_XIN_TOC = "skill_yi_xin_toc",
  SKILL_ZHI_YIN_TOC = "skill_zhi_yin_toc",
  SKILL_JING_MENG_A_TOC = "skill_jing_meng_a_toc",
  SKILL_JING_MENG_B_TOC = "skill_jing_meng_b_toc",
  SKILL_JIE_DAO_SHA_REN_A_TOC = "skill_jie_dao_sha_ren_a_toc",
  SKILL_JIE_DAO_SHA_REN_B_TOC = "skill_jie_dao_sha_ren_b_toc",
  SKILL_JIAO_JI_A_TOC = "skill_jiao_ji_a_toc",
  SKILL_JIAO_JI_B_TOC = "skill_jiao_ji_b_toc",
  SKILL_MIAO_BI_QIAO_BIAN_A_TOC = "skill_miao_bi_qiao_bian_a_toc",
  SKILL_MIAO_BI_QIAO_BIAN_B_TOC = "skill_miao_bi_qiao_bian_b_toc",
  SKILL_JIN_BI_A_TOC = "skill_jin_bi_a_toc",
  SKILL_JIN_BI_B_TOC = "skill_jin_bi_b_toc",
  SKILL_MIAO_SHOU_A_TOC = "skill_miao_shou_a_toc",
  SKILL_MIAO_SHOU_B_TOC = "skill_miao_shou_b_toc",
  SKILL_JIN_KOU_YI_KAI_A_TOC = "skill_jin_kou_yi_kai_a_toc",
  SKILL_JIN_KOU_YI_KAI_B_TOC = "skill_jin_kou_yi_kai_b_toc",
  SKILL_WAIT_FOR_JIANG_HU_LING_A_TOC = "skill_wait_for_jiang_hu_ling_a_toc",
  SKILL_JIANG_HU_LING_A_TOC = "skill_jiang_hu_ling_a_toc",
  SKILL_WAIT_FOR_JIANG_HU_LING_B_TOC = "skill_wait_for_jiang_hu_ling_b_toc",
  SKILL_JIANG_HU_LING_B_TOC = "skill_jiang_hu_ling_b_toc",
  SKILL_JI_BAN_A_TOC = "skill_ji_ban_a_toc",
  SKILL_JI_BAN_B_TOC = "skill_ji_ban_b_toc",
  SKILL_YOU_DAO_TOC = "skill_you_dao_toc",
  SKILL_BO_AI_A_TOC = "skill_bo_ai_a_toc",
  SKILL_BO_AI_B_TOC = "skill_bo_ai_b_toc",
  SKILL_GUANG_FA_BAO_A_TOC = "skill_guang_fa_bao_a_toc",
  SKILL_WAIT_FOR_GUANG_FA_BAO_B_TOC = "skill_wait_for_guang_fa_bao_b_toc",
  SKILL_GUANG_FA_BAO_B_TOC = "skill_guang_fa_bao_b_toc",
  SKILL_WAIT_FOR_QIANG_LING_TOC = "skill_wait_for_qiang_ling_toc",
  SKILL_QIANG_LING_TOC = "skill_qiang_ling_toc",
  SKILL_JIAN_REN_A_TOC = "skill_jian_ren_a_toc",
  SKILL_JIAN_REN_B_TOC = "skill_jian_ren_b_toc",
  SKILL_SOU_JI_A_TOC = "skill_sou_ji_a_toc",
  SKILL_SOU_JI_B_TOC = "skill_sou_ji_b_toc",
  SKILL_DUI_ZHENG_XIA_YAO_A_TOC = "skill_dui_zheng_xia_yao_a_toc",
  SKILL_DUI_ZHENG_XIA_YAO_B_TOC = "skill_dui_zheng_xia_yao_b_toc",
  SKILL_DUI_ZHENG_XIA_YAO_C_TOC = "skill_dui_zheng_xia_yao_c_toc",
  SKILL_DU_JI_A_TOC = "skill_du_ji_a_toc",
  SKILL_WAIT_FOR_DU_JI_B_TOC = "skill_wait_for_du_ji_b_toc",
  SKILL_DU_JI_B_TOC = "skill_du_ji_b_toc",
  SKILL_DU_JI_C_TOC = "skill_du_ji_c_toc",

  //tos协议
}

//系统事件，用于程序控制
export enum SystemEvent {
  ADD_ROOM_POSITION = "add_room_position",
}

//游戏事件，触发扳机
export enum GameEvent {
  ACCEPT_MESSAGE = "accept_message",
  ACCEPT_RED_MESSAGE = "accept_red_message",
  ACCEPT_BLUE_MESSAGE = "accept_blue_message",
  ACCEPT_BLACK_MESSAGE = "accept_black_message",
}
